# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-GraphMan
version:      0.02
version_from: GraphMan.pm
installdirs:  site
requires:
    Tk:                            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
